// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIIW1qWXoF320J9p2t_j7jZMqXpKZcgHM',
    appId: '1:405687163858:web:576632d8455c99b8aa860b',
    messagingSenderId: '405687163858',
    projectId: 'desago-app',
    authDomain: 'desago-app.firebaseapp.com',
    storageBucket: 'desago-app.firebasestorage.app',
    measurementId: 'G-7P4T7NFGXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDstEiw2g_X5vfDoL_58h8RuzcG3DlwiVQ',
    appId: '1:405687163858:android:ce3d74b9ec3612c1aa860b',
    messagingSenderId: '405687163858',
    projectId: 'desago-app',
    storageBucket: 'desago-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmwIehumT-XnE5rb9dir8vk__S93Ua56E',
    appId: '1:405687163858:ios:c66d574413dfe8e8aa860b',
    messagingSenderId: '405687163858',
    projectId: 'desago-app',
    storageBucket: 'desago-app.firebasestorage.app',
    iosBundleId: 'com.desago.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmwIehumT-XnE5rb9dir8vk__S93Ua56E',
    appId: '1:405687163858:ios:c66d574413dfe8e8aa860b',
    messagingSenderId: '405687163858',
    projectId: 'desago-app',
    storageBucket: 'desago-app.firebasestorage.app',
    iosBundleId: 'com.desago.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIIW1qWXoF320J9p2t_j7jZMqXpKZcgHM',
    appId: '1:405687163858:web:57dea4de5112f02caa860b',
    messagingSenderId: '405687163858',
    projectId: 'desago-app',
    authDomain: 'desago-app.firebaseapp.com',
    storageBucket: 'desago-app.firebasestorage.app',
    measurementId: 'G-2SWRD3Z1MM',
  );

}